language: "en-US"
reviews:
  profile: "chill"
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    include:
      - "src/**"
    exclude:
      - "tests/**"
  chat:
    auto_reply: true