id: ai-summarizer
namespace: contextkeeper

inputs:
  - id: dev_mode
    type: BOOLEAN
    defaults: true

tasks:
  - id: fetch_github
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: python:3.9
    beforeCommands:
      - pip install PyGithub python-dotenv
    commands:
      # Mount backend scripts volume or clone repo. For local dev, assuming scripts are accessible or copied.
      # Since we are running in docker, we need to handle file access.
      # For simplicity in this "local" setup, we'll assume we can pass the script content or run it if kestra is local.
      # However, standard Kestra runs in Docker.
      # Let's assume the user mapped the volume or we use a simpler approach of inline script for now if path is hard.
      # BUT, the user has the files locally.
      # Better approach for local Kestra: Use Process runner if Kestra is running on host, OR assume Volume Mount.
      # Given user context: "running Kestra locally".
      # Let's try to use the Local Process runner if possible, or just standard python if kestra is raw jar.
      # If Kestra is Docker, we need volumes.
      # Let's stick to the prompt plan: "Run python backend/scripts/..."
      # We will use the `Process` runner assuming Kestra is running as a local binary or has access to host files.
      - python backend/scripts/github_collector.py --recent-activity "{{ inputs.dev_mode }}"
    env:
      GITHUB_TOKEN: "{{ envs.GITHUB_TOKEN }}"
      GITHUB_REPO: "{{ envs.GITHUB_REPO }}"

  - id: fetch_slack
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: python:3.9
    beforeCommands:
      - pip install slack-sdk python-dotenv
    commands:
      - python backend/scripts/slack_collector.py --recent-activity
    env:
      SLACK_TOKEN: "{{ envs.SLACK_TOKEN }}"
      SLACK_CHANNELS: "{{ envs.SLACK_CHANNELS }}"

  - id: fetch_notion
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: python:3.9
    beforeCommands:
      - pip install notion-client python-dotenv
    commands:
      - python backend/scripts/notion_collector.py --recent-activity
    env:
      NOTION_TOKEN: "{{ envs.NOTION_TOKEN }}"

  - id: aggregate_data
    type: io.kestra.core.tasks.debugs.Return
    format: |
      Here is the daily digest:
      
      GITHUB: {{ outputs.fetch_github.vars.stdout }}
      SLACK: {{ outputs.fetch_slack.vars.stdout }}
      NOTION: {{ outputs.fetch_notion.vars.stdout }}

  - id: summarize_updates
    type: io.kestra.plugin.core.http.Request
    uri: "https://router.huggingface.co/hf-inference/models/facebook/bart-large-cnn"
    method: POST
    headers:
      Authorization: "Bearer {{ envs.HUGGINGFACE_API_KEY }}"
    contentType: application/json
    body: |
      {
        "inputs": {{ ("Summarize the following project updates into a concise daily briefing with action items:\n\n" ~ outputs.aggregate_data.value) | json }},
        "parameters": {
          "max_length": 500,
          "temperature": 0.7
        }
      }

  - id: log-summary
    type: io.kestra.core.tasks.log.Log
    message: |
      --- AI GENERATED SUMMARY ---
      {{ outputs.summarize_updates.body }}
      ----------------------------

triggers:
  - id: daily-schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *" # Runs every day at 9 AM
namespace: contextkeeper

variables:
  github_update: "New PR #42: Feature/AI-Agent - Implements basic Kestra flow structure."
  slack_update: "Channel #general: @user1 asked about the new deployment schedule."
  notion_update: "Page 'Q3 Roadmap': Added 'AI Integration' to priority list."

tasks:
  - id: aggregate_data
    type: io.kestra.core.tasks.debugs.Return
    format: |
      Here is the daily digest from your tools:
      
      GITHUB: {{ vars.github_update }}
      
      SLACK: {{ vars.slack_update }}
      
      NOTION: {{ vars.notion_update }}

  - id: summarize_updates
    type: io.kestra.plugin.core.http.Request
    uri: "https://router.huggingface.co/hf-inference/models/facebook/bart-large-cnn"
    method: POST
    headers:
      Authorization: "Bearer hf_your_api_key_here"
    contentType: application/json
    body: |
      {
        "inputs": {{ ("Summarize the following project updates into a concise daily briefing with action items if any:\n\n" ~ outputs.aggregate_data.value) | json }},
        "parameters": {
          "max_length": 200,
          "temperature": 0.7
        }
      }

  - id: log-summary
    type: io.kestra.core.tasks.log.Log
    message: |
      --- AI GENERATED SUMMARY ---
      {{ outputs.summarize_updates.body }}
      ----------------------------

triggers:
  - id: daily-schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *" # Runs every day at 9 AM
